Week4/d05/coffeeshop/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

root to: 'beans#index'

get 'beans',  to: 'beans#index'
get 'beans/new', to: 'beans#new'
post 'beans',  to: 'beans#create'
get 'beans/:id', to: 'beans#show', as: :bean
get 'beans/:id/edit', to: 'beans#edit', as: :edit_bean
put 'beans', to: 'beans#update'
patch 'beans', to: 'beans#update'
delete 'beans/:id', to: 'beans#destroy'

end

Week4/d05/coffeeshop/app/models/bean.rb
class Bean < ApplicationRecord
end

Week4/d05/coffeeshop/app/controllers/beans_controller.rb
class BeansController < ApplicationController

  def index
    @beans = Bean.all
  end

  def new
    @beans = Bean.new
  end

  def create
    @beans = Bean.new(bean_params)

    if @bean.save
      redirect_to_beans_path
    else
      render :new
    end
  end

  def show
    @bean = Bean.find(params[:id])
  end

  def delete
    @bean = Bean.find(params[:id])
    @bean.destroy
    redirect_to_beans_path
  end

  def edit
    @bean = Bean.find(params[:id])
  end

  def update
    @bean = Bean.find(params[:id])

    if @bean.update_attributes(bean_params)
      redirect_to_beans_path
    else
      render :edit
    end
  end

  private

  def bean_params
    params.require(:bean).permit(:name, :roast, :origin, :quantity)
  end

end

Week4/d05/coffeeshop/app/helpers/beans_helper.rb
module BeansHelper
end

Week4/d05/coffeeshop/app/views/beans/edit.html.erb
<h1>Edit the <%= @bean.name %> Bean</h1>

<%= form_for @bean do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :roast %>
    <%= f.text_field :roast %>
  </div>
  <div>
    <%= f.label :origin %>
    <%= f.text_field :origin %>
  </div>
  <div>
    <%= f.label :quantity %>
    <%= f.text_field :quantity %>
  </div>
  <%= f.submit "Update Bean!" %>
<% end %>

<%= link_to "Back to the list!", beans_path %>

Week4/d05/coffeeshop/app/views/beans/index.html.erb
<h1>Today's Beans</h1>

<ul>
  <% @beans.each do |bean| %>
    <li>
      <strong><%= link_to bean.name, bean_path(bean) %></strong>&nbsp; - &nbsp;<%= bean.roast %>
      | <%= link_to "Edit this bean!", edit_bean_path(bean) %>
    </li>
  <% end %>
</ul>

Week4/d05/coffeeshop/app/views/beans/new.html.erb
<h1>Add a new bean!</h1>

<%= form_for @bean do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :roast %>
    <%= f.text_field :roast %>
  </div>
  <div>
    <%= f.label :origin %>
    <%= f.text_field :origin %>
  </div>
  <div>
    <%= f.label :quantity %>
    <%= f.text_field :quantity %>
  </div>
  <%= f.submit "Add New Bean!" %>
<% end %>

<%= link_to "Back to the list!", beans_path %>

Week4/d05/coffeeshop/app/views/beans/show.html.erb
<h1><%= @bean.name %></h1>

<p>This coffee is a <%= @bean.roast %> roast from <%= @bean.origin %>, and we have <%= @bean.quantity %> pounds available.</p>
<%= link_to "Delete this bean!", bean_path(@bean), method: :delete, data: { confirm: "Are you sure you want to delete this bean?"} %>

<%= link_to "Back to the list!", beans_path %>

Week4/d05/coffeeshop/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Coffeeshop</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
    <%= link_to "Make a new bean", beans_new_path %>
  </body>
</html>